apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/f3t9n2z9/test11:latest1
          ports:
            - containerPort: 80
